

# 数据源
spring:
  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://124.223.105.57:3306/bfit?useUnicode=true&characterEncoding=utf-8
    username: dbmasteruser
    password: (C~|1>?E8_2[aY=6~bfhwqP`n,xM3MBM
    url: jdbc:mysql://ls-194d3368c12c7fe31f57f6e2621f55f5c3cd9063.c7y9o8ohmkhm.us-west-2.rds.amazonaws.com/bd3
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: bd3admin
#    password: ED%gFXN!BA_qP@uo7S
#    url: jdbc:postgresql://ls-77b2c0b75da82d2894ed93435b4a26270b91de81.c7y9o8ohmkhm.us-west-2.rds.amazonaws.com/bd3
#    username: postgres
#    password: mysecretpassword
#    url: jdbc:postgresql://localhost:5432/bd3
#    driver-class-name: org.postgresql.Driver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 12
      # 空闲时保持最小连接数
      minimum-idle: 5
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 20000
      # 测试sql
      connection-test-query: select 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
server:
  port: 8883


logging:
  level:
    com:
      bfit:
        recommand:
          data.mapper: debug
